import image1 from "../../../images/ShopCategories/babycare.avif"
import image2 from "../../../images/ShopCategories/walkers.jpg"
import image3 from "../../../images/ShopCategories/mediciness.jpg"
import image4 from "../../../images/ShopCategories/whelchair.webp"
import image5 from "../../../images/ShopCategories/surgical.png"
import image6 from "../../../images/ShopCategories/Surface06.svg"
import image7 from "../../../images/ShopCategories/Surface07.svg"
import image8 from "../../../images/ShopCategories/Surface08.svg"
import image9 from "../../../images/ShopCategories/Surface09.svg"
import image10 from"../../../images/ShopCategories/Surface10.svg"
import card1 from "../../../images/sallar/Surface 1.svg"
import card2 from "../../../images/sallar/Surface 2.svg"
import card3 from "../../../images/sallar/Surface 3.svg"
import card4 from "../../../images/sallar/Surface 4.svg"
import card5 from "../../../images/sallar/Surface 5.svg"


export const FirstPageData = [
    {
        id: 1,
        image: image1,
        title: 'Hisense 58" Class 4K UHD LCD Roku Smart TV HDR R',
        brand: 'SAMSUNG',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 2,
        image: image2,
        title: 'Logitech Pro Stream Webcam 1080P Camera for HD Video',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 3,
        image: image3,
        title: 'Black Radiance True Complexion™ Loose Setting',
        brand: 'SONY',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 4,
        image: image4,
        title: 'Mei Apothecary Mini Jade Facial Roller Beauty Tool',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 5,
        image: image5,
        title: 'Versed Dew Point Moisturizing Gel-Cream, Green',
        brand: 'ROLEX',
        price: '$18.124',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },

    {
        id: 6,
        image: image6,
        title: 'Hisense 58" Class 4K UHD LCD Roku Smart TV HDR R',
        brand: 'SAMSUNG',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 7,
        image: image7,
        title: 'Versace Bright Crystal Eau de Toilette, Perfume for Women',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 8,
        image: image8,
        title: 'Salon Perfect X Dippin Dots Nail Lacquer, 556 Cotton Candy',
        brand: 'SONY',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 9,
        image: image9,
        title: 'Versace Bright Crystal Eau de Toilette, Perfume for Women',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 10,
        image: image10,
        title: 'Revlon One-Step Volumizer Original 1.0 Hair Dryer and Hot',
        brand: 'ROLEX',
        price: '$18.124',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },

    {
        id: 11,
        image: card1,
        title: 'Versed Dew Point Moisturizing Gel-Cream, Green',
        brand: 'ROLEX',
        price: '$18.124',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },

    {
        id: 12,
        image: card2,
        title: 'Hisense 58" Class 4K UHD LCD Roku Smart TV HDR R',
        brand: 'SAMSUNG',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 13,
        image: card3,
        title: 'Versace Bright Crystal Eau de Toilette, Perfume for Women',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 14,
        image: card4,
        title: 'Salon Perfect X Dippin Dots Nail Lacquer, 556 Cotton Candy',
        brand: 'SONY',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 15,
        image: card5,
        title: 'Versace Bright Crystal Eau de Toilette, Perfume for Women',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 16,
        image: image8,
        title: 'Salon Perfect X Dippin Dots Nail Lacquer, 556 Cotton Candy',
        brand: 'SONY',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 17,
        image: image2,
        title: 'Logitech Pro Stream Webcam 1080P Camera for HD Video',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 18,
        image: image7,
        title: 'Versace Bright Crystal Eau de Toilette, Perfume for Women',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 19,
        image: card2,
        title: 'Hisense 58" Class 4K UHD LCD Roku Smart TV HDR R',
        brand: 'SAMSUNG',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 20,
        image: image1,
        title: 'Hisense 58" Class 4K UHD LCD Roku Smart TV HDR R',
        brand: 'SAMSUNG',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },

    {
        id: 21,
        image: image1,
        title: 'Hisense 58" Class 4K UHD LCD Roku Smart TV HDR R',
        brand: 'SAMSUNG',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 22,
        image: image2,
        title: 'Logitech Pro Stream Webcam 1080P Camera for HD Video',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 23,
        image: image3,
        title: 'Black Radiance True Complexion™ Loose Setting',
        brand: 'SONY',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 24,
        image: image4,
        title: 'Mei Apothecary Mini Jade Facial Roller Beauty Tool',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 25,
        image: image5,
        title: 'Versed Dew Point Moisturizing Gel-Cream, Green',
        brand: 'ROLEX',
        price: '$18.124',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },

    {
        id: 26,
        image: image6,
        title: 'Hisense 58" Class 4K UHD LCD Roku Smart TV HDR R',
        brand: 'SAMSUNG',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 27,
        image: image7,
        title: 'Versace Bright Crystal Eau de Toilette, Perfume for Women',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 28,
        image: image8,
        title: 'Salon Perfect X Dippin Dots Nail Lacquer, 556 Cotton Candy',
        brand: 'SONY',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 29,
        image: image9,
        title: 'Versace Bright Crystal Eau de Toilette, Perfume for Women',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 310,
        image: image10,
        title: 'Revlon One-Step Volumizer Original 1.0 Hair Dryer and Hot',
        brand: 'ROLEX',
        price: '$18.124',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },

    {
        id: 311,
        image: card1,
        title: 'Versed Dew Point Moisturizing Gel-Cream, Green',
        brand: 'ROLEX',
        price: '$18.124',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },

    {
        id: 312,
        image: card2,
        title: 'Hisense 58" Class 4K UHD LCD Roku Smart TV HDR R',
        brand: 'SAMSUNG',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 313,
        image: card3,
        title: 'Versace Bright Crystal Eau de Toilette, Perfume for Women',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 314,
        image: card4,
        title: 'Salon Perfect X Dippin Dots Nail Lacquer, 556 Cotton Candy',
        brand: 'SONY',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 315,
        image: card5,
        title: 'Versace Bright Crystal Eau de Toilette, Perfume for Women',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 316,
        image: image8,
        title: 'Salon Perfect X Dippin Dots Nail Lacquer, 556 Cotton Candy',
        brand: 'SONY',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 317,
        image: image2,
        title: 'Logitech Pro Stream Webcam 1080P Camera for HD Video',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 318,
        image: image7,
        title: 'Versace Bright Crystal Eau de Toilette, Perfume for Women',
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 319,
        image: card2,
        title: 'Hisense 58" Class 4K UHD LCD Roku Smart TV HDR R',
        brand: 'SAMSUNG',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },
    {
        id: 320,
        image: image1,
        title: 'Hisense 58" Class 4K UHD LCD Roku Smart TV HDR R',
        brand: 'SAMSUNG',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
    },


]