import image1 from "../../../images/ShopCategories/babycare.avif"
import image2 from "../../../images/ShopCategories/walkers.jpg"
import image3 from "../../../images/ShopCategories/mediciness.jpg"
import image4 from "../../../images/ShopCategories/whelchair.webp"
import image5 from "../../../images/major/medicine.jpeg"
import image6 from "../../../images/major/surgical.webp"
import image7 from "../../../images/major/walker.jpg"
import image8 from "../../../images/major/toilet.avif"
import baby1 from "../../../images/major/baby1.jpg"
import baby2 from "../../../images/major/baby2.jpg"
import baby3 from "../../../images/major/baby3.jpg"
import walker1 from "../../../images/major/walker1.jpg"
import walker2 from "../../../images/major/walker2.jpg"
import walker3 from "../../../images/major/walker3.jpg"
import med1 from "../../../images/major/med1.jpg"
import med2 from "../../../images/major/med2.jpg"
import med3 from "../../../images/major/med3.jpg"
import chair1 from "../../../images/major/wheel1.jpg"
import chair2 from "../../../images/major/wheel2.jpg"
import chair3 from "../../../images/major/wheel3.jpg"
import surg1 from "../../../images/major/surg1.jpg"
import surg2 from "../../../images/major/surg2.jpg"
import surg3 from "../../../images/major/surg3.jpg"
import wheel1 from "../../../images/major/seat1.jpg"
import wheel2 from "../../../images/major/seat2.jpg"
import wheel3 from "../../../images/major/seat3.jpg"








export const FirstPageData = [
    {
        id: 1,
        image: image1,
        title: 'Round-the-clock emergency services for critical care',
        brand: 'GentleCare',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: baby1,
        product2: baby2,
        product3: baby3,
    },
    {
        id: 2,
        image: image2,
        title: 'Lightweight and stable walkers for patient assistance.',
        brand: 'CareMove',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: walker1,
        product2: walker2,
        product3: walker3,
    },
    {
        id: 3,
        image: image3,
        title: 'Prescription and over-the-counter medications.',
        brand: 'HealthMate',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: med1,
        product2: med2,
        product3: med3,
    },
    {
        id: 4,
        image: image4,
        title: 'Durable and comfortable wheelchairs for mobility needs.',
        brand: 'Mobility Aid Co',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: chair1,
        product2: chair2,
        product3: chair3,
    },
    {
        id: 5,
        image: image5,
        title: 'Prescription and over-the-counter medicines for all needs.',
        brand: 'Health Plus',
        price: '$18.124',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: med1,
        product2: med2,
        product3: med3,

    },

    {
        id: 6,
        image: image6,
        title: 'High-quality surgical instruments for precise procedures.',
        brand: 'MediCare Pro',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: surg1,
        product2: surg2,
        product3: surg3,
    },
    {
        id: 7,
        image: image7,
        title: 'Providing support and stability for patient mobility.',
        brand: 'Patient Walker',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: walker1,
        product2: walker2,
        product3: walker3,
    },
    {
        id: 8,
        image: image8,
        title: 'Comfortable and hygienic toilet seats for patient care.',
        brand: 'HygieneFirst',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: wheel1,
        product2: wheel2,
        product3: wheel3,
    },
    {
        id: 10,
        image: image1,
        title: 'Round-the-clock emergency services for critical care',
        brand: 'GentleCare',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: baby1,
        product2: baby2,
        product3: baby3,
    },
    {
        id: 20,
        image: image2,
        title: 'Lightweight and stable walkers for patient assistance.',
        brand: 'CareMove',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: walker1,
        product2: walker2,
        product3: walker3,
    },
    {
        id: 30,
        image: image3,
        title: 'Prescription and over-the-counter medications.',
        brand: 'HealthMate',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: med1,
        product2: med2,
        product3: med3,
    },
    {
        id: 40,
        image: image4,
        title: 'Durable and comfortable wheelchairs for mobility needs.',
        brand: 'Mobility Aid Co',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: chair1,
        product2: chair2,
        product3: chair3,
    },
    {
        id: 50,
        image: image5,
        title: 'Prescription and over-the-counter medicines for all needs.',
        brand: 'Health Plus',
        price: '$18.124',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: med1,
        product2: med2,
        product3: med3,

    },

    {
        id: 60,
        image: image6,
        title: 'High-quality surgical instruments for precise procedures.',
        brand: 'MediCare Pro',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: surg1,
        product2: surg2,
        product3: surg3,
    },
    {
        id: 70,
        image: image7,
        title: 'Providing support and stability for patient mobility.',
        brand: 'Patient Walker',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: walker1,
        product2: walker2,
        product3: walker3,
    },
    {
        id: 80,
        image: image8,
        title: 'Comfortable and hygienic toilet seats for patient care.',
        brand: 'HygieneFirst',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: wheel1,
        product2: wheel2,
        product3: wheel3,
    },
    {
        id: 11,
        image: image1,
        title: 'Round-the-clock emergency services for critical care',
        brand: 'GentleCare',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: baby1,
        product2: baby2,
        product3: baby3,
    },
    {
        id: 21,
        image: image2,
        title: 'Lightweight and stable walkers for patient assistance.',
        brand: 'CareMove',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: walker1,
        product2: walker2,
        product3: walker3,
    },
    {
        id: 311,
        image: image3,
        title: 'Prescription and over-the-counter medications.',
        brand: 'HealthMate',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: med1,
        product2: med2,
        product3: med3,
    },
    {
        id: 411,
        image: image4,
        title: 'Durable and comfortable wheelchairs for mobility needs.',
        brand: 'Mobility Aid Co',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: chair1,
        product2: chair2,
        product3: chair3,
    },
    {
        id: 51,
        image: image5,
        title: 'Prescription and over-the-counter medicines for all needs.',
        brand: 'Health Plus',
        price: '$18.124',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: med1,
        product2: med2,
        product3: med3,

    },

    {
        id: 61,
        image: image6,
        title: 'High-quality surgical instruments for precise procedures.',
        brand: 'MediCare Pro',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: surg1,
        product2: surg2,
        product3: surg3,
    },
    {
        id: 71,
        image: image7,
        title: 'Providing support and stability for patient mobility.',
        brand: 'Patient Walker',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: walker1,
        product2: walker2,
        product3: walker3,
    },
    {
        id: 81,
        image: image8,
        title: 'Comfortable and hygienic toilet seats for patient care.',
        brand: 'HygieneFirst',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: wheel1,
        product2: wheel2,
        product3: wheel3,
    },
    {
        id: 12,
        image: image1,
        title: 'Round-the-clock emergency services for critical care',
        brand: 'GentleCare',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: baby1,
        product2: baby2,
        product3: baby3,
    },
    {
        id: 22,
        image: image2,
        title: 'Lightweight and stable walkers for patient assistance.',
        brand: 'CareMove',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: walker1,
        product2: walker2,
        product3: walker3,
    },
    {
        id: 32,
        image: image3,
        title: 'Prescription and over-the-counter medications.',
        brand: 'HealthMate',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: med1,
        product2: med2,
        product3: med3,
    },
    {
        id: 42,
        image: image4,
        title: 'Durable and comfortable wheelchairs for mobility needs.',
        brand: 'Mobility Aid Co',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: chair1,
        product2: chair2,
        product3: chair3,
    },
    {
        id: 52,
        image: image5,
        title: 'Prescription and over-the-counter medicines for all needs.',
        brand: 'Health Plus',
        price: '$18.124',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: med1,
        product2: med2,
        product3: med3,

    },

    {
        id: 62,
        image: image6,
        title: 'High-quality surgical instruments for precise procedures.',
        brand: 'MediCare Pro',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: surg1,
        product2: surg2,
        product3: surg3,
    },
    {
        id: 722,
        image: image7,
        title: 'Providing support and stability for patient mobility.',
        brand: 'Patient Walker',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: walker1,
        product2: walker2,
        product3: walker3,
    },
    {
        id: 82,
        image: image8,
        title: 'Comfortable and hygienic toilet seats for patient care.',
        brand: 'HygieneFirst',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        product1: wheel1,
        product2: wheel2,
        product3: wheel3,
    },
   

]