import image1 from "../../../images/ShopCategories/babycare.avif"
import image2 from "../../../images/ShopCategories/walkers.jpg"
import image3 from "../../../images/ShopCategories/mediciness.jpg"
import image4 from "../../../images/ShopCategories/whelchair.webp"
import image5 from "../../../images/ShopCategories/surgical.png"
import logo from   "../../../images/graph 1.svg"
import card1 from  "../../../images/sallar/Surface 1.svg"
import card2 from  "../../../images/sallar/Surface 2.svg"
import card3 from  "../../../images/sallar/Surface 3.svg"


export const ListData = [
    
   {
        id: 1,
        image: image1,
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2:"SSD/12GB RAM/Windows 11)",
        brand: 'SAMSUNG',
        price: '$899.99',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },
    {
        id: 2,
        image: image2,
        brand: 'EASTSPORT',
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2: "SSD/12GB RAM/Windows 11)",
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },
    {
        id: 3,
        image: image3,
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2: "SSD/12GB RAM/Windows 11)",
        brand: 'SONY',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },
    {
        id: 4,
        image: image4,
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2: "SSD/12GB RAM/Windows 11)",
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },
    {
        id: 5,
        image: image5,
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2: "SSD/12GB RAM/Windows 11)",
        brand: 'ROLEX',
        price: '$18.124',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },
    {
        id: 6,
        image: card2,
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2: "SSD/12GB RAM/Windows 11)",
        brand: 'SAMSUNG',
        price: '$899.99',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },
    {
        id: 7,
        image: card3,
        brand: 'EASTSPORT',
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2: "SSD/12GB RAM/Windows 11)",
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },
    {
        id: 8,
        image: card1,
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2: "SSD/12GB RAM/Windows 11)",
        brand: 'SONY',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },

    {
        id: 9,
        image: image1,
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2: "SSD/12GB RAM/Windows 11)",
        brand: 'SAMSUNG',
        price: '$899.99',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },
    {
        id: 10,
        image: image2,
        brand: 'EASTSPORT',
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2: "SSD/12GB RAM/Windows 11)",
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },
    {
        id: 11,
        image: image3,
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2: "SSD/12GB RAM/Windows 11)",
        brand: 'SONY',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },
    {
        id: 12,
        image: image4,
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2: "SSD/12GB RAM/Windows 11)",
        brand: 'EASTSPORT',
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },
    {
        id: 13,
        image: image5,
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2: "SSD/12GB RAM/Windows 11)",
        brand: 'ROLEX',
        price: '$18.124',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },
    {
        id: 14,
        image: card2,
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2: "SSD/12GB RAM/Windows 11)",
        brand: 'SAMSUNG',
        price: '$899.99',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },
    {
        id: 15,
        image: card3,
        brand: 'EASTSPORT',
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2: "SSD/12GB RAM/Windows 11)",
        price: '$32.50',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },
    {
        id: 16,
        image: card1,
        title: 'Lenovo IdeaPad 3 15.6" Laptop - Sand (Intel Core i7-1165G7/512GB ',
        title2: "SSD/12GB RAM/Windows 11)",
        brand: 'SONY',
        price: '$399.00',
        originalPrice: '$45',
        reviews: "3,014 reviews",
        rating: 5,
        button: "Add to Cart",
        text: "Add to Wishlist",
        logo: logo,
        text1: "Compare",
        list1: "16-core Neural Engine for advanced machine learning",
        list2: "8GB of unified memory so everything you do is fast and fluid",
        list3: "256GB of super-fast SSD storage launches apps and opens files",
        list4: "7-core GPU with up to 5 times faster graphics for graphics-intensive",
    },
]